spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.diet.app.dto
  datasource:
    url: jdbc:postgresql://localhost:5432/diet
    username: diet
    password: diet

  jpa:
    hibernate:
      ddl-auto: update